### ISSUE TITLE
Tracking: most backends have `react-dnd` as a (peer-)dependency

### ISSUE THREAD

**Issue by cormacrelf** [cormacrelf/angular-skyhook#1]
They are actually compatible, but they yell about unsatisfied peer dependencies when you're installing, or they actually install `react-dnd`. 

- [x] https://github.com/LouisBrunner/dnd-multi-backend/issues/21
- [x] https://github.com/yahoo/react-dnd-touch-backend/issues/96
- [x] https://github.com/zyzo/react-dnd-mouse-backend/issues/9
- [x] https://github.com/react-dnd/react-dnd/issues/1084
- [x] react-dnd-test-backend as well
